
site_name: Zero to Mastery Learn Machine Learning and Deep Learning Concepts
site_url: 
site_description: Learn important machine learning concepts hands-on by writing PyTorch code.

repo_url: https://github.com/JamorMoussa/docs
repo_name: JamorMoussa/docs

docs_dir: docs

theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
  palette:
    primary: black

  font:
      text: "Segoe UI"


extra_css:
 - css/extra.css



markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences


  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search

edit_uri: ""

site_author: Moussa JAMOR

nav:

  - Home:
    - 'index.md'

####################################################################################
  
  - Deep Learning:
    - Home: 'deep_learning/index.md'
    
    - Sequence Models:
      - deep_learning/seq_models/Seqeunce-Models-Specialization-with-Andrew-Ng.ipynb
    
    - AutoEncoders:
      - deep_learning/auto_encoders/AutoEncoders-Architecture-In-DeepLearning.ipynb

  
####################################################################################

  - Large Language Models:
    - 'llms/attention-is-all-you-need.ipynb'
    - 'llms/rag-pytorch-from-scratch.ipynb'
  

####################################################################################
  
  - Papers: 
    - Home: 'papers/index.md'
    - Graph Neural Networks:
      - 'papers/graph_conv_net/graph_conv_net.ipynb'
    - Optimzation Methods:
      - 'papers/opt_methods/index.md'
      - 'papers/opt_methods/adadelta.ipynb'



extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moussa-jamor-b17a58253/
    - icon: fontawesome/brands/github
      link: https://github.com/JamorMoussa/


