site_name: Zero to Mastery Learn Machine Learning and Deep Learning Concepts
site_url: 
site_description: Learn important machine learning concepts hands-on by writing PyTorch code.

repo_url: https://github.com/JamorMoussa/ML-DL-Concepts
repo_name: JamorMoussa/ML-DL-Concepts

theme:
  name: material
  # logo: assets/ztm-logo-and-pytorch-logo.png
  # favicon: assets/ztm-logo-and-pytorch-logo.png
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    # - toc.integrate
  palette:
    primary: black

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search
 - social

edit_uri: ""

nav:
  - Home: 
    - Moussa Jamor: 'index.md'
    - 'home/extra_activities.md'

####################################################################################

  - Machine Learning:
    - Home: 'machine_learning/index.md'


####################################################################################
  
  - Deep Learning:
    - Home: 'deep_learning/index.md'
    - Graph Neural Networks:
      - Introduction: 'deep_learning/gnn/index.md'
      - GCN:
        - 'deep_learning/gnn/Introduction to Graph Neural Network with Pytorch.ipynb'
  

####################################################################################


  - Natural Language Processing:
    - Home: 'nlp/index.md'
  

####################################################################################  

  - Computer Vision:
    - Home: 'computer_vision/index.md'
  

####################################################################################

  - Data Engineering: 
    - Home: 'data_engineering/index.md'
  

####################################################################################
  
  - Papers: 
    - Home: 'papers/index.md'
    - Graph Neural Networks:
      - 'papers/graph_conv_net/graph_conv_net.ipynb'

####################################################################################

  - Projects:
    - Home: 'projects/index.md'
    - NeuraNet: 'projects/neura_net/index.md'

site_author: Moussa JAMOR

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moussa-jamor-b17a58253/
    - icon: fontawesome/brands/github
      link: https://github.com/JamorMoussa/
    # - icon: fontawesome/brands/youtube
    #   link: https://www.youtube.com/channel/UCr8O8l5cCX85Oem1d18EezQ